-- INDEXACION
-- LOS INDICES SE CREAN TAMBIEN AL CREAR UNA TABLA PUESTO QUE CUANDO PONEMOS
-- UNA CLAVE PRIMARIA, SE CREA UN INDICE POR CADA UNA
CREATE INDEX IND_COLOR ON pieza(color); 

-- LOS INDICES DE DOBLE ENTRADA NO SON BUENOS PARA PREGUNTAR POR LA SEGUNDA
-- DADO QUE PRIMERO RECORRE LA PRIMERA ENTRADA COMPLETA, POR ESO ES RECOMENDABLE
-- PARA HACER UNA COMPROBACION DOBLE 
-- PODEMOS PONER DESC PARA HACER UNA ORDENACION INVERSA
CREATE INDEX IND_COL_CIUDAD ON pieza(color, ciudad);

SELECT * from user_indexes;

-- NUNCA INDEXAR POR CLAVE PRIMARIA TRABAJANDO EN ORACLE

--BORRAR INDICE
DROP INDEX IND_COLOR;

-- INDICES ESPECIFICOS
-- INVERTIDO; Cuando  hay mucho paralelismo, ya que le doy la vuelta y lo cuento en una
-- pag aleatoria, para si hya muchas apps que quieren el mismo bloque.
CREATE INDEX nombre ON alumnos(DNI) reverse;

-- ORGANIZAMOS POR INDICE (LO ORGANIZA POR LA CLAVE PRIMARIA)
CREATE TABLE proveedor(...) ORGANIZATION INDEX;